# Copyright 2019 Ecosoft Co., Ltd (http://ecosoft.co.th/)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html)

{
    'name': 'NPD Standard Module Install Party Addons ',
    'version': '14.0.1',
    'author': 'NPD',
    'license': 'AGPL-3',
    'website': '',
    'category': 'Modules',
    'depends': [
        'account_menu_hide',
        'l10n_th_asset_register_report',
        'npd_account_inherit',
        'npd_account_invoice_reset_tax',
        'npd_asset_duplicate',
        'npd_customer_pricelist',
        'npd_std_show_only_child',
        'npd_stock_request_cost_price',
        'npd_partner_name_unq',
        'npd_std_asset_stock_receipt',
        'npd_sale_quotation_date',
        'npd_std_asset_set_durable_articles',
        'npd_std_asset_free_field',

        'npd_company_custom',
        'npd_generate_subsequences',
        'npd_purchase_discount',
        'npd_std_access_confirm_rfq',
        'npd_std_add_priority_pr',
        'npd_std_default_uom_pr',
        'npd_std_po_document_type',
        'npd_std_stock_inventory',
        'npd_std_cheque_qweb',
        'npd_std_pnd_qweb',

        'account_analytic_distribution_required',
        'account_analytic_sequence',
        'account_analytic_wip',
        'account_asset_management_transfer',
        'account_cash_basis_group_base_line',
        'account_comment_template',
        'account_due_list',
        'account_invoice_report_due_list',
        'account_invoice_section_sale_order',
        'purchase_tier_validation',
        'sale_tier_validation',
        'account_operating_unit',
        'account_cost_center',
        'account_payment_term_discount',
        'account_payment_term_extension',
        'account_reconciliation_widget',
        'analytic_base_department',
        'analytic_tag_dimension',
        'analytic_tag_dimension_enhanced',
        'aspl_product_alert_qty',
        'auditlog',
        'auto_backup',
        'base_cancel_confirm',
        'base_exception',
        'base_product_mass_addition',
        'bi_stock_expiry_report',
        'currency_rate_inverted',
        'currency_rate_update',
        'dev_inventory_ageing_report',
        'excel_import_export',
        'fiscal_year_sequence_extensible',
        'hide_any_menu',
        'hr_department_code',
        'hr_organizational_chart',
        'inbox_notif_email',
        'ks_account_dashboard',
        'l10n_th_currency_rate_update',
        'ls_web_m2x_options_config',
        'mis_builder',
        'mis_builder_budget',
        'mis_builder_budget_activity_group',
        'muk_rest',
        'partner_industry_secondary',
        'partner_phone_extension',
        'product_brand',
        'product_category_code',
        'product_category_product_link',
        'product_category_tax',
        'product_code_unique',
        'product_configurator',
        'product_configurator_purchase',
        'product_cost_security',
        'product_sequence',
        'product_state',
        'product_variant_default_code',
        'product_variant_sale_price',
        'product_warranty',
        'product_weight',
        'purchase_order_archive',
        'purchase_order_line_menu',
        'purchase_order_line_price_history',
        'purchase_order_uninvoiced_amount',
        'purchase_reception_notify',
        'purchase_reception_status',
        'purchase_request_tier_validation',
        'purchase_requisition_tier_validation',
        'purchase_tier_validation',
        'purchase_work_acceptance',
        'sale_comment_template',
        'sale_commitment_date_mandatory',
        'sale_discount_display_amount',
        'sale_exception',
        'sale_force_invoiced',
        'sale_invoice_blocking',
        'sale_last_price_info',
        'sale_order_archive',
        'sale_order_line_date',
        'sale_order_line_description',
        'sale_order_line_menu',
        'sale_order_line_note',
        'sale_order_line_variant_description',
        'sale_order_note_template',
        'sale_order_revision',
        'sale_partner_incoterm',
        'sale_tier_validation',
        'scrap_reason_code',
        'stock_available',
        'stock_cycle_count',
        'stock_inventory_preparation_filter',
        'stock_move_line_auto_fill',
        'stock_picking_back2draft',
        'stock_picking_cancel_confirm',
        'stock_picking_filter_lot',
        'stock_putaway_hook',
        'stock_restrict_lot',
        'stock_return_request',
        'stock_valuation_layer_by_category',
        'web_widget_many2many_tags_link',

        'stock_location_children',
        'stock_location_lockdown',
        'stock_picking_invoice_link',
    ],
    'installable': True,
}
